"""Pytest fixtures for the backend test suite.

Two flavours of fixture live here:
* ``async_client`` (Phase 1) — no DB, monkey-patched downstream pings.
* ``integration_client`` (Phase 2) — real MySQL via the docker compose
  network. Drops every row from the identity tables before each test
  so the audit_log + invariants can be exercised against a clean slate.

Integration tests require ``CORELAB_DATABASE_URL`` to point at a
reachable MySQL (in CI this is corelab-mysql via docker network); they
skip themselves when the URL is unset.
"""

from __future__ import annotations

import os
from collections.abc import AsyncIterator

import pytest
import pytest_asyncio
from corelab_backend.config import get_settings
from corelab_backend.db import get_engine, get_session_factory
from corelab_backend.main import create_app
from corelab_backend.security import hash_password
from httpx import ASGITransport, AsyncClient
from sqlalchemy import text


@pytest_asyncio.fixture
async def async_client() -> AsyncIterator[AsyncClient]:
    """Plain ASGI client — no DB; suitable for /healthz and unit tests."""
    app = create_app()
    transport = ASGITransport(app=app)
    async with AsyncClient(transport=transport, base_url="http://testserver") as client:
        yield client


def _has_real_db() -> bool:
    url = os.environ.get("CORELAB_DATABASE_URL", "")
    return "asyncmy" in url and "localhost" not in url


@pytest_asyncio.fixture
async def integration_client(monkeypatch: pytest.MonkeyPatch) -> AsyncIterator[AsyncClient]:
    """ASGI client backed by the real MySQL container.

    Routes the runtime engine through ``CORELAB_MIGRATION_DATABASE_URL``
    (full grants) so test fixtures can DELETE FROM the identity tables
    before each test — the runtime user deliberately lacks DELETE
    (Phase 2 invariant #8) so it cannot tear down its own state.
    """
    if not _has_real_db():
        pytest.skip("integration tests need a real CORELAB_DATABASE_URL")

    migration_url = os.environ.get("CORELAB_MIGRATION_DATABASE_URL")
    if migration_url:
        monkeypatch.setenv("CORELAB_DATABASE_URL", migration_url)

    get_settings.cache_clear()
    get_engine.cache_clear()
    get_session_factory.cache_clear()

    engine = get_engine()
    async with engine.begin() as conn:
        # FK-reverse: Phase 5 first (reservation FK→account_link + server +
        # gpu + user), Phase 4 next, Phase 3, Phase 2.
        for table in (
            "alert_event",
            "agent_policy",
            "reservation",
            "account_link_request",
            "account_link",
            "authorized_key_entry",
            "physical_account",
            "agent_capability",
            "gpu",
            "server_admin_grant",
            "enrollment_token",
            "server",
            "audit_log",
            "ssh_public_key",
            "setup_token",
            "registration_invite",
            "user",
            "lab",
        ):
            await conn.execute(text(f"DELETE FROM {table}"))

    app = create_app()
    transport = ASGITransport(app=app)
    async with AsyncClient(transport=transport, base_url="http://testserver") as client:
        yield client

    await engine.dispose()
    get_engine.cache_clear()
    get_session_factory.cache_clear()
    get_settings.cache_clear()


@pytest_asyncio.fixture
async def seeded_admin(integration_client: AsyncClient) -> dict[str, str | int]:
    """Insert a ready-to-login lab_admin (alice) via /setup/init."""
    resp = await integration_client.post(
        "/api/v1/setup/init",
        json={
            "lab_name": "Test Lab",
            "lab_slug": "test-lab",
            "admin_username": "alice",
            "admin_email": "alice@test.com",
            "admin_display_name": "Alice",
            "admin_password": "AlicePass!2024",  # pragma: allowlist secret
        },
    )
    assert resp.status_code == 201
    data = resp.json()
    # Sanity: bcrypt hash actually generated by security.hash_password.
    assert hash_password("x").startswith("$2b$")
    return {
        "admin_id": data["admin"]["id"],
        "lab_id": data["lab_id"],
        "password": "AlicePass!2024",  # pragma: allowlist secret
    }
